# parameters necessary for NN setup
num_neurons = [50, 50]
loss_function = "MSELoss"

[neural_network.optimizer]
type = "Adam"
learning_rate = 0.01

[dataset]
# parameters necessary to load dataset
filelist = false
dirpath = "/largedisk/julius_w/Development/conc2RDF/training_data"

[learning]
epochs = 5000
print_progress = true
train_selection = [10.0, 30.0, 50.0, 70.0, 90.0]
test_selection = [20.0, 40.0, 60.0, 80.0, 100.0]
num_runs = 20

# [learning.early_stopping]
# patience = 20
# min_delta = 0.000000001
# counter = 0 #should always be set to 0

[learning.scheduler]
type = "ReduceLROnPlateau"

[learning.scheduler.parameters]
mode = "min"
factor = 0.1
patience = 5
verbose = true
